//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC_technic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentModel()
        {
            this.EquipmentAccounting = new HashSet<EquipmentAccounting>();
        }
    
        public int ID_ModelE { get; set; }
        public Nullable<int> EquipmentType { get; set; }
        public string EquipmentName { get; set; }
        public string Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentAccounting> EquipmentAccounting { get; set; }
        public virtual EquipmentType EquipmentType1 { get; set; }
    }
}
