//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC_technic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAccounting
    {
        public int ID { get; set; }
        public Nullable<int> Equipment { get; set; }
        public string SerialNumber { get; set; }
        public string InventoryNumber { get; set; }
        public Nullable<int> EquipmentStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual EquipmentModel EquipmentModel { get; set; }
        public virtual Status Status { get; set; }
    }
}
